import {
  Atom,
  BookOpen,
  Brain,
  BracketsCurly,
  Bug,
  Calculator,
  ChartLineUp,
  Circuitry,
  Cloud,
  Code,
  Cpu,
  Cube,
  Database,
  FileCode,
  Flask,
  Function as FunctionIcon,
  Gear,
  GitBranch,
  Globe,
  Graph,
  HardDrive,
  Eye,
  Laptop,
  Network,
  Robot,
  ShieldCheck,
  Sparkle,
  Terminal,
  TerminalWindow,
  TreeStructure,
  WifiHigh,
  Wrench,
} from '@phosphor-icons/react'

export const ADMIN_ICON_OPTIONS = [
  { name: 'Atom', label: 'Atom', Icon: Atom },
  { name: 'BookOpen', label: 'Book', Icon: BookOpen },
  { name: 'Brain', label: 'Brain', Icon: Brain },
  { name: 'BracketsCurly', label: 'Code Brackets', Icon: BracketsCurly },
  { name: 'Bug', label: 'Debugging', Icon: Bug },
  { name: 'Calculator', label: 'Calculator', Icon: Calculator },
  { name: 'ChartLineUp', label: 'Chart', Icon: ChartLineUp },
  { name: 'Circuitry', label: 'Circuitry', Icon: Circuitry },
  { name: 'Cloud', label: 'Cloud', Icon: Cloud },
  { name: 'Code', label: 'Code', Icon: Code },
  { name: 'Cube', label: 'Cube', Icon: Cube },
  { name: 'Database', label: 'Database', Icon: Database },
  { name: 'FileCode', label: 'File Code', Icon: FileCode },
  { name: 'Flask', label: 'Lab', Icon: Flask },
  { name: 'FunctionIcon', label: 'Function', Icon: FunctionIcon },
  { name: 'Gear', label: 'Systems', Icon: Gear },
  { name: 'GitBranch', label: 'Git Branch', Icon: GitBranch },
  { name: 'Globe', label: 'Web', Icon: Globe },
  { name: 'Graph', label: 'Graph', Icon: Graph },
  { name: 'HardDrive', label: 'Operating System', Icon: HardDrive },
  { name: 'Eye', label: 'Vision', Icon: Eye },
  { name: 'Laptop', label: 'Laptop', Icon: Laptop },
  { name: 'Network', label: 'Network', Icon: Network },
  { name: 'Cpu', label: 'Processor', Icon: Cpu },
  { name: 'Robot', label: 'Robot', Icon: Robot },
  { name: 'ShieldCheck', label: 'Security', Icon: ShieldCheck },
  { name: 'Sparkle', label: 'Sparkle', Icon: Sparkle },
  { name: 'Terminal', label: 'Terminal', Icon: Terminal },
  { name: 'TerminalWindow', label: 'Terminal Window', Icon: TerminalWindow },
  { name: 'TreeStructure', label: 'Tree', Icon: TreeStructure },
  { name: 'WifiHigh', label: 'Networking', Icon: WifiHigh },
  { name: 'Wrench', label: 'Tools', Icon: Wrench },
]

export function getIconOptionByName(name) {
  return ADMIN_ICON_OPTIONS.find(option => option.name === name) ?? ADMIN_ICON_OPTIONS[0]
}

export function getIconNameForComponent(Icon) {
  return ADMIN_ICON_OPTIONS.find(option => option.Icon === Icon)?.name ?? null
}
